# Generated by Django 2.1.3 on 2018-11-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='acticle',
            new_name='artical',
        ),
    ]
