# Generated by Django 2.1.3 on 2018-11-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20181116_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artical',
            new_name='articale',
        ),
        migrations.RenameField(
            model_name='articale',
            old_name='artical_author',
            new_name='articale_author',
        ),
    ]
