# Generated by Django 2.1.3 on 2018-11-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20181116_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='articale',
            name='image',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
