# Generated by Django 2.1.3 on 2018-11-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_articale_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default='1', upload_to=''),
            preserve_default=False,
        ),
    ]
